stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    - src/prepare.py
    params:
    - data.raw_path
    - data.split_random_state
    - data.test_size
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
    - models/scaler.pkl
  validate_data:
    cmd: python src/validate_data.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/validate_data.py
    outs:
    - deepchecks_reports/data_integrity.html
    - deepchecks_reports/train_test_validation.html
  validate_model:
    cmd: python src/validate_model.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - models/best_model.pkl
    - src/validate_model.py
    outs:
    - deepchecks_reports/model_evaluation.html
  train_random_forest:
    cmd: python src/train_random_forest.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/train_random_forest.py
    params:
    - data.split_random_state
    - random_forest
    outs:
    - models/random_forest.pkl
    metrics:
    - results/random_forest_metrics.json:
        cache: false
  train_catboost:
    cmd: python src/train_catboost.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/train_catboost.py
    params:
    - catboost
    outs:
    - models/catboost.pkl
    - results/feature_importance.csv:
        cache: false
    metrics:
    - results/catboost_metrics.json:
        cache: false
  select_best_model:
    cmd: python src/select_best_model.py
    deps:
    - models/catboost.pkl
    - models/random_forest.pkl
    - results/catboost_metrics.json
    - results/random_forest_metrics.json
    - src/select_best_model.py
    outs:
    - models/best_model.pkl
    - results/model_comparison.csv:
        cache: false
    metrics:
    - results/best_model.json:
        cache: false
